version: '3.8'

services:
  app:
    image: 'simplelibrary:latest'
    build:
      context: .     
    container_name: simplelibrary_app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/simple-library
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - 8080:8080

  db:
    image: postgres
    container_name: simplelibrary_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simple-library
    ports:
      - 5432:5432